### ISSUE TITLE
question about kvell latency

### ISSUE THREAD

**Issue by anoyiuhu** [BLepers/KVell#3]
Hi, 

   I just test kvell in two optane p4800x 375G SSDs with ycsb-a, but found that the latency was very high, Do you think the result is reasonable? (From paper 6.5.1 section, the kvell average latency can achieve an average latency of 158us. ) 

I test ycsb-a workload 20,000,000 request in database of 100,000,000 elements.

 Here is ycsb-a result
<img width="859" alt="Screen Shot 2020-05-04 at 4 34 23 PM" src="https://user-images.githubusercontent.com/64774259/80948787-635a0700-8e25-11ea-9366-1a0a7796b7de.png">
I modify code in print_stats function in stats.c, adding three statistical outputs

    1.median--cycles_to_us(stats.timing_value[last*50/100])
    2. p99--cycles_to_us(stats.timing_value[last*50/100])
    3. p999--cycles_to_us(stats.timing_value[p999]); p999=(int)last*99.9/100
So when the ycsb-a test finished, I can get throughput, avg-latency, median, p90,p99,p999 automatically.

Here is configuration for kvell runtime(I directly use the default setting in your code)

1.   Configuration for yscb-a uniform in two optane disk
   1.1 Page cache size: 30 GB
   1.2  Workers: 8 working on 2 disks  
   1.3 IO configuration: 64 queue depth (capped: yes, extra waiting: no)
   1.4  Queue configuration: 256 maximum pending callbaks per worker
   1.5 Datastructures: 3 (memory index) 3 (pagecache)
   1.6 Thread pinning: yes
   1.7 Bench: YCSB (100000000 elements)

2.  Configuration for  yscb-a zipfian in two optane disks
   2.1  Page cache size: 30 GB
   2.2 Workers: 8 working on 2 disks
   2.3  IO configuration: 64 queue depth (capped: yes, extra waiting: no)
   2.4 Queue configuration: 256 maximum pending callbaks per worker
   2.5 Datastructures: 3 (memory index) 3 (pagecache)
   2.6 Thread pinning: yes
   2.7 Bench: YCSB (100000000 elements)

Looking for your reply.
Best regards

**Comment by BLepers** [comment]
Thanks for your interest. The latencies you observe are not abnormally high (11ms for 99.9 is not too bad), but you can probably reduce them with the following:
* reduce the queue depth to 32
* if latency is still high, reduce the number of workers to 2 per disk (4 workers in total)
I think that the maximum number of pending callbacks per worker is dependent on the queue depth, but if it is not, you can try to reduce this number (e.g., 128 or 64 instead of 256).

With these, your latency numbers should be ~1/4 of what you currently have. You can also play a bit with these three parameters (e.g., queue depth of 16). At some point, it's a tradeoff between maximum throughput and latency (if you set the queue depth to a very low number, your latency will be very good, but throughput will start to go down).

**Comment by anoyiuhu** [comment]
Ok, got it
Thanks for your reply
